## 1. Credit card applications
<p>Commercial banks receive <em>a lot</em> of applications for credit cards. Many of them get rejected for many reasons, like high loan balances, low income levels, or too many inquiries on an individual's credit report, for example. Manually analyzing these applications is mundane, error-prone, and time-consuming (and time is money!). Luckily, this task can be automated with the power of machine learning and pretty much every commercial bank does so nowadays. In this notebook, we will build an automatic credit card approval predictor using machine learning techniques, just like the real banks do.</p>
<p><img src="https://assets.datacamp.com/production/project_558/img/credit_card.jpg" alt="Credit card being held in hand"></p>
<p>We'll use the <a href="http://archive.ics.uci.edu/ml/datasets/credit+approval">Credit Card Approval dataset</a> from the UCI Machine Learning Repository.

## 2. Import Pandas

1. Import pandas and alias it as pd
2. Load the dataset cc_approvals.data into a cc_apps dataframe.
    - Set the header argument to None.
3. Print the first five rows.
4. Drop the columns 11 and 13.

In [4]:
import pandas as pd
df = pd.read_csv("datasets/cc_approvals.data" ,header=None)
df.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [5]:
df1 = df.drop([11, 13], axis=1)
df1

0      1       2  3  4   5   6     7  8  9   10 12   14 15
0    b  30.83   0.000  u  g   w   v  1.25  t  t   1  g    0  +
1    a  58.67   4.460  u  g   q   h  3.04  t  t   6  g  560  +
2    a  24.50   0.500  u  g   q   h  1.50  t  f   0  g  824  +
3    b  27.83   1.540  u  g   w   v  3.75  t  t   5  g    3  +
4    b  20.17   5.625  u  g   w   v  1.71  t  f   0  s    0  +
..  ..    ...     ... .. ..  ..  ..   ... .. ..  .. ..  ... ..
685  b  21.08  10.085  y  p   e   h  1.25  f  f   0  g    0  -
686  a  22.67   0.750  u  g   c   v  2.00  f  t   2  g  394  -
687  a  25.25  13.500  y  p  ff  ff  2.00  f  t   1  g    1  -
688  b  17.92   0.205  u  g  aa   v  0.04  f  f   0  g  750  -
689  b  35.00   3.375  u  g   c   h  8.29  f  f   0  g    0  -

[690 rows x 14 columns]

## 3. Explore the dataset

1. Print the basic statistics.
2. Print the information of the dataset.
3. Print the last 17 rows.

In [6]:
df1.describe()

2           7          10             14
count  690.000000  690.000000  690.00000     690.000000
mean     4.758725    2.223406    2.40000    1017.385507
std      4.978163    3.346513    4.86294    5210.102598
min      0.000000    0.000000    0.00000       0.000000
25%      1.000000    0.165000    0.00000       0.000000
50%      2.750000    1.000000    0.00000       5.000000
75%      7.207500    2.625000    3.00000     395.500000
max     28.000000   28.500000   67.00000  100000.000000

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       690 non-null    object 
 1   1       690 non-null    object 
 2   2       690 non-null    float64
 3   3       690 non-null    object 
 4   4       690 non-null    object 
 5   5       690 non-null    object 
 6   6       690 non-null    object 
 7   7       690 non-null    float64
 8   8       690 non-null    object 
 9   9       690 non-null    object 
 10  10      690 non-null    int64  
 11  12      690 non-null    object 
 12  14      690 non-null    int64  
 13  15      690 non-null    object 
dtypes: float64(2), int64(2), object(10)
memory usage: 75.6+ KB


In [8]:
df1.tail(17)

0      1       2  3  4   5   6      7  8  9   10 12   14 15
673  ?  29.50   2.000  y  p   e   h  2.000  f  f   0  g   17  -
674  a  37.33   2.500  u  g   i   h  0.210  f  f   0  g  246  -
675  a  41.58   1.040  u  g  aa   v  0.665  f  f   0  g  237  -
676  a  30.58  10.665  u  g   q   h  0.085  f  t  12  g    3  -
677  b  19.42   7.250  u  g   m   v  0.040  f  t   1  g    1  -
678  a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  g   50  -
679  a  20.08   1.250  u  g   c   v  0.000  f  f   0  g    0  -
680  b  19.50   0.290  u  g   k   v  0.290  f  f   0  g  364  -
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  g  537  -
682  b  17.08   3.290  u  g   i   v  0.335  f  f   0  g    2  -
683  b  36.42   0.750  y  p   d   v  0.585  f  f   0  g    3  -
684  b  40.58   3.290  u  g   m   v  3.500  f  f   0  s    0  -
685  b  21.08  10.085  y  p   e   h  1.250  f  f   0  g    0  -
686  a  22.67   0.750  u  g   c   v  2.000  f  t   2  g  394  -
687  a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  g    1  -
688  b  17.92   0.205  u  g  aa   v  0.040  f  f   0  g  750  -
689  b  35.00   3.375  u  g   c   h  8.290  f  f   0  g    0  -

## 4. Train Test Split

Do not split the dataset into X and y, just split the original dataset.

random_state=42

test_size=0.33

In [9]:
#from sklearn.model_selection import train_test_split

#train, test = train_test_split(df, test_size=0.33, random_state=42)

## 5. Handling Missing Values

Convert any '?' to a NaN value from both training and testing sets.

In [10]:
import numpy as np

df1.replace('?', np.nan, inplace=True)

## 6. Handling Missing Values

Impute the numerical data for both training and testing sets with mean value.

In [11]:
df1.isna().sum().sum()

54

In [12]:
for column in df1. columns:
    if df1 [column].dtype in ['int64','float64']:
        mean_value = df1 [column].mean ()
        df1 [column].replace(np.nan, mean_value, inplace=True) 
    else:
        mode_value = df1 [column].mode() [0]
        df1[column].replace (np.nan, mode_value, inplace=True)

## 7. Handling Missing Values

Impute the categorical data for both training and testing sets with mode value.

In [13]:
#up

## 8. Encoding

The columns 0, 3, 4, 5, 6, 8, 9, and 12 are categorical, there are several methods we can use to encode the categorical columns. One of the method called get_dummies().

Use get_dummies() function to convert the categorical columns to a numerical columns (for training the machine learning algorithms).

Do not forget to convert both training and testing sets.

In [14]:
cat_columns=[0,3,4,5,6,8,9,12]
df1=pd.get_dummies(df1,columns= cat_columns)

## 9. Split into features and target

X_train and y_train will take 462 rows.
X_test and y_test will take 228 rows.

In [16]:
from sklearn.model_selection import train_test_split
X = df1.drop(15, axis=1)
y=df1.iloc[:,15]
X_train , X_test, y_train , y_test = train_test_split(X, y, test_size=0.33 , random_state=42)

## 10. Normalization

In [19]:
from sklearn.preprocessing import MinMaxScaler
X_train.columns=X_train.columns.astype(str)
X_test.columns=X_test.columns.astype(str)

scaler=MinMaxScaler()
scaledX_train=scaler.fit_transform(X_train)
scaledX_test=scaler.fit_transform(X_test)

## 11. Train a Logistic Regression

In [21]:
from sklearn.linear_model import LogisticRegression

model= LogisticRegression()
model.fit(scaledX_train, y_train)

LogisticRegression()

## 12. Make predictions and evaluate the Logistic Regression Model

In [23]:
predictions = model.predict(scaledX_test)
predictions

array([False, False, False,  True, False, False, False, False,  True,
        True, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False,  True, False,  True,
       False,  True,  True, False, False,  True, False, False,  True,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False,

In [31]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix, classification_report


accuracy = accuracy_score(y_test, predictions)
f1 = f1_score(y_test, predictions, average='weighted')
precision = precision_score(y_test, predictions, average='weighted')
recall = recall_score(y_test, predictions, average='weighted')
confusion_mat = confusion_matrix(y_test, predictions)
classification_rep = classification_report(y_test, predictions)

print("Accuracy:", accuracy)
print("F1-score:", f1)
print("Precision:", precision)
print("Recall:", recall)
print("Confusion Matrix:\n", confusion_mat)
print("Classification Report:\n", classification_rep)

Accuracy: 1.0
F1-score: 1.0
Precision: 1.0
Recall: 1.0
Confusion Matrix:
 [[180   0]
 [  0  48]]
Classification Report:
               precision    recall  f1-score   support

       False       1.00      1.00      1.00       180
        True       1.00      1.00      1.00        48

    accuracy                           1.00       228
   macro avg       1.00      1.00      1.00       228
weighted avg       1.00      1.00      1.00       228



## 13. Repeat the steps 11 and 12 for SVM, DT, and RF

### svm :

In [30]:
from sklearn.svm import SVC

svm_model = SVC ()
svm_model.fit(scaledX_train,y_train)

SVC()

In [41]:
predictions = model.predict(scaledX_test)

accuracy = accuracy_score(y_test, predictions)
f1 = f1_score(y_test, predictions, average='weighted')
precision = precision_score(y_test, predictions, average='weighted')
recall = recall_score(y_test, predictions, average='weighted')
confusion_mat = confusion_matrix(y_test, predictions)
classification_rep = classification_report(y_test, predictions)

print("Accuracy:", accuracy)
print("F1-score:", f1)
print("Precision:", precision)
print("Recall:", recall)
print("Confusion Matrix:\n", confusion_mat)
print("Classification Report:\n", classification_rep)

Accuracy: 1.0
F1-score: 1.0
Precision: 1.0
Recall: 1.0
Confusion Matrix:
 [[180   0]
 [  0  48]]
Classification Report:
               precision    recall  f1-score   support

       False       1.00      1.00      1.00       180
        True       1.00      1.00      1.00        48

    accuracy                           1.00       228
   macro avg       1.00      1.00      1.00       228
weighted avg       1.00      1.00      1.00       228



### DT

In [35]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier ()
model.fit(scaledX_train,y_train)

DecisionTreeClassifier()

In [38]:
predictions = model.predict(scaledX_test)

accuracy = accuracy_score(y_test, predictions)
f1 = f1_score(y_test, predictions, average='weighted')
precision = precision_score(y_test, predictions, average='weighted')
recall = recall_score(y_test, predictions, average='weighted')
confusion_mat = confusion_matrix(y_test, predictions)
classification_rep = classification_report(y_test, predictions)

print("Accuracy:", accuracy)
print("F1-score:", f1)
print("Precision:", precision)
print("Recall:", recall)
print("Confusion Matrix:\n", confusion_mat)
print("Classification Report:\n", classification_rep)

Accuracy: 1.0
F1-score: 1.0
Precision: 1.0
Recall: 1.0
Confusion Matrix:
 [[180   0]
 [  0  48]]
Classification Report:
               precision    recall  f1-score   support

       False       1.00      1.00      1.00       180
        True       1.00      1.00      1.00        48

    accuracy                           1.00       228
   macro avg       1.00      1.00      1.00       228
weighted avg       1.00      1.00      1.00       228



### RF

In [39]:
from sklearn.ensemble import RandomForestClassifier

model= RandomForestClassifier()
model.fit(scaledX_train, y_train)

RandomForestClassifier()

In [40]:
predictions = model.predict(scaledX_test)

accuracy = accuracy_score(y_test, predictions)
f1 = f1_score(y_test, predictions, average='weighted')
precision = precision_score(y_test, predictions, average='weighted')
recall = recall_score(y_test, predictions, average='weighted')
confusion_mat = confusion_matrix(y_test, predictions)
classification_rep = classification_report(y_test, predictions)

print("Accuracy:", accuracy)
print("F1-score:", f1)
print("Precision:", precision)
print("Recall:", recall)
print("Confusion Matrix:\n", confusion_mat)
print("Classification Report:\n", classification_rep)

Accuracy: 1.0
F1-score: 1.0
Precision: 1.0
Recall: 1.0
Confusion Matrix:
 [[180   0]
 [  0  48]]
Classification Report:
               precision    recall  f1-score   support

       False       1.00      1.00      1.00       180
        True       1.00      1.00      1.00        48

    accuracy                           1.00       228
   macro avg       1.00      1.00      1.00       228
weighted avg       1.00      1.00      1.00       228

